### ISSUE TITLE
Multiple SQL injection vulnerabilities

### ISSUE THREAD

**Issue by fgeek** [mblankleder/hamradio-logbook#1]
Hello,

You should sanitize user input in SQL queries using something similar to 

[mysqli.real-escape-string](http://www.php.net/manual/en/mysqli.real-escape-string.php)

Please see:
- http://en.wikipedia.org/wiki/SQL_injection
- https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet

Contact me in case you need more information. This is after login, but should still be fixed :)

**Comment by mblankleder** [comment]
Hello,
Thanks for the advise.
You're right, there's a lot of stuff to improve in this code I'm in debt with it but for the moment it's on hold.
Regards
Michel

**Comment by fgeek** [comment]
@mblankleder Might be best to remove this project from GitHub if you don't plan to maintain the codebase.

**Comment by mblankleder** [comment]
@fgeek Thanks for your comments. My motivation to leave it there is that it might be useful for someone.

**Comment by fgeek** [comment]
If you don't fix basic critical security vulnerabilities then I'd say it is not useful. It might even be harmful. I don't waste anymore of your time. Have a nice day and good luck to your current projects :)
